### ISSUE TITLE
NPM package down

### ISSUE THREAD

**Issue by jerrykeys** [ThRintelen/ngx-metafizzy-flickity#10]
The npm package is not available on npm anymore. On `npm install` I get the console message

```
npm ERR! code ENOVERSIONS
npm ERR! No versions available for ngx-metafizzy-flickity
```

and on its npm page `https://www.npmjs.com/package/ngx-metafizzy-flickity` it returns an 404

**Comment by ThRintelen** [comment]
i have publish the package again, please try it.

**Comment by jerrykeys** [comment]
Thanks a ton! It's now available. However the project I am working on is still on Angular 11 due to some other dependencies, and the 2.0 branch of your package won't work with Angular 11 anymore. It there a possibility to restore the latest v1 package version?

**Comment by ThRintelen** [comment]
the latest version should use the latest angular version.
What error you got? I think it should also work with angular 11.

An other way is to fork this repo and the use the old tag.

**Comment by jerrykeys** [comment]
It said something about not matching dependencies when I recall it correctly. However I just copied the directive for now and switch back to the package at a later point when I will be able to upgrade to Angular 12. Once again thank you for providing the project!
