### ISSUE TITLE
Performance issue mobile

### ISSUE THREAD

**Issue by paimfp** [ThRintelen/ngx-metafizzy-flickity#12]
Hi!
I am seeing very poor performance on mobile devices, the carousel animations feel very laggy. Desktop is fine.

I suspect that the events in the carousel autoplay are triggering a LOT of angular change detection...

Does someone have a clue how to improve that?

**Comment by ThRintelen** [comment]
Can you share your implementation / configuration? I don´t use it with autoplay.

**Comment by paimfp** [comment]
My config for the autoplay one is like so:

```
{
    "wrapAround": true,
    "autoPlay": 5000,
    "accessibility": false,
    "imagesLoaded": true,
    "prevNextButtons": true,
    "pageDots": true
}
```

Also I have a method to grab the flickity instance when it's ready and add some events like so:


```
flickReady(flickity) {
    this.bannerFlickity = flickity;
    this.bannerFlickity.on('staticClick', (event, pointer, cellElement, cellIndex) => DO_SOMETHING
    this.bannerFlickity.on('pointerDown', (event, pointer) => this.bannerFlickity.stopPlayer());
    this.bannerBlurSubscription = fromEvent(this.bannerFlickityEl.nativeElement, 'focusout').subscribe(() => {
        this.bannerFlickity.playPlayer();
    })
    this.bannerFocusSubscription = fromEvent(this.bannerFlickityEl.nativeElement, 'focusin').subscribe(() => {
        this.bannerFlickity.stopPlayer();
    })
}
```

The reason I am suspecting of change detection is that I put this in the component with autoplay to log the checks angular does:

```
ngAfterViewChecked() {
    console.log("Checked");
}
```
And I got like 1500 logs after 1 min. Then I put this in another carousel in the same page without autoplay, and the result was the same, so I am not sure it has to do with autoplay exactly... (We're using 3 carousels in the page).
Compare that with 60checks/min from another page without carousels, diff is huge.

You can see in [this vídeo](https://drive.google.com/file/d/1Fg-JHEmoy9uvP2888SK5Y7U_NFr_SEAq/view?usp=sharing), that the checks triggers very fast when slide changes, but also fast when slide does not change (although a little slower) when I clicked the next button, the autoplay is stoped.

Using autoPlay: false, I got 800 checks/min, roughly half compared with autoplay On.
It seems the autoplay increase the checks, and make the lags more noticeable because of the movement of the slides.
But even without autoplay, the checks from change detection are pretty hight...

I put the log in a component C and got different results changing the autoPlay config in another component A, that in theory has a different instance of flickity, right? I didn't get this yet...

**Comment by ThRintelen** [comment]
What cd strategy do you use in your component?

**Comment by paimfp** [comment]
> What cd strategy do you use in your component?

Default

**Comment by ThRintelen** [comment]
Have you try OnPush as cd strategy?

**Comment by paimfp** [comment]
Tested just now with Observable and async pipe approach using ChangeDetectionStrategy.OnPush, and removing some keyboard event listeners, unfortunately, the same result...

**Comment by paimfp** [comment]
Maybe it's a weird combination of how flickity itself triggers things and Angular dirty checking...
Were you able to log the checks in some random component of yours? Just to see if results are consistent...

**Comment by ThRintelen** [comment]
I try my demo in this repo. You can start it with "ng serve" and see two flickity slider.
The ngAfterViewChecked shows the logs too, but there are no performance issues, also not on mobile devices.

It is true, that flickity and angular is not the best combination, but until today we don´t found a better solution. The pain is noch big enougth to build an own slider :-)

I don´t think, that the problem comes with my flickity directive.

**Comment by paimfp** [comment]
Hi @ThRintelen !
Sorry for the delay on this.

I've been thinking in the cause/solution, and I think the cause is really what we discussed: the flickity library has a lot of asynchronous operations which triggers change detection unnecessary in Angular because of how change detection works. For example: https://github.com/metafizzy/flickity/blob/master/dist/flickity.pkgd.js#L3546

For the solution I used the `runOutsideAngular` function of the NgZone, with this I am getting none of those huge detections, the only thing I had to do was to add one change detection manually on a modal component I have that was not updating correctly.

I am not allowed to push to this repo, and maybe it's not a perfect solution too, but I am putting this here if someone needs this performance improvement.

This is the code I came up with:

![image](https://user-images.githubusercontent.com/48572841/147491009-3d05c417-fc72-448d-b2de-036dba90365d.png)

**Comment by ThRintelen** [comment]
Hi,

i can see the change detection problems in the example of this package too, if i use ngAfterViewInit. But, why you use it?
The example works without problems with ngOnInit.

Thanks for sharing your solution.

I think runOutsideAngular is a good solution to use external Vanilla JS or old jQuery packages.

If you create a stackblitz with your working example and the problem / solution, i would take a look....

**Comment by paimfp** [comment]
Sure, I'm a little out of time now, but will setup a stackblitz as soon as I can.

The ngAfterViewInit is just to remove the setTimeout. There's nothing to do with the performance actually.
Without the setTimeout on ngOnInit it was erroring because the element was not there yet.
It just felt a more Angular way to do it, but it was previously working fine too.

**Comment by paimfp** [comment]
Hi @ThRintelen , sorry for huge delay.
Here is the stackblitz with the changes (zone.runOutsideAngular and added a staticClick event emmiter inside zone.run to Angular track changes from there), I am very happy with the results:

https://stackblitz.com/edit/github-hpczna-rbexwq

**Comment by ThRintelen** [comment]
thanks for the input. i will check it if i update the plugin to angular 14.
Fell free to create a pull request, or is there still an privilege problem?

**Comment by paimfp** [comment]
Nice!
What you mean by privilege problem?

**Comment by ThRintelen** [comment]
Hi @paimfp 

I have update the package to angular 14 and add your cod. it looks good.
Feel free to test the new version (angular 14).

**Comment by paimfp** [comment]
Hi @ThRintelen

Thanks for the update, I am glad to know all went well.
I'll check it for sure!

See you!
