### ISSUE TITLE
Can't import the named export 'ChangeDetectorRef' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by ngdevc** [ThRintelen/ngx-metafizzy-flickity#13]
My Angular version is 10, and i'm getting this error after this package's been installed.

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 52:171-191
Can't import the named export 'ChangeDetectorRef' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 59:83-103
Can't import the named export 'ChangeDetectorRef' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 55:18-27
Can't import the named export 'Directive' from non EcmaScript module (only default export is available)        

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 52:145-158
Can't import the named export 'ElementRef' from non EcmaScript module (only default export is available)       

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 59:58-71
Can't import the named export 'ElementRef' from non EcmaScript module (only default export is available)       

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 21:25-37
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)     

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 22:26-38
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)     

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 60:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 73:18-26
Can't import the named export 'NgModule' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 62:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 64:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 23:22-34
Can't import the named export 'Subscription' from non EcmaScript module (only default export is available)     

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 42:32-44
Can't import the named export 'debounceTime' from non EcmaScript module (only default export is available)     

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 41:22-31
Can't import the named export 'fromEvent' from non EcmaScript module (only default export is available)        

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 42:18-27
Can't import the named export 'startWith' from non EcmaScript module (only default export is available)        

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 52:204-222
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)  

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 69:141-159
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)  

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 54:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 72:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 53:25-48
Can't import the named export 'ɵɵngDeclareDirective' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 52:25-46
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 69:22-43
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 71:22-44
Can't import the named export 'ɵɵngDeclareInjector' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/ngx-metafizzy-flickity/fesm2015/ngx-metafizzy-flickity.mjs 70:22-44
Can't import the named export 'ɵɵngDeclareNgModule' from non EcmaScript module (only default export is available)
    
    ERROR in node_modules/ngx-metafizzy-flickity/src/app/ngx-flickity/ngx-flickity.directive.d.ts:16:21

**Comment by ThRintelen** [comment]
Which version of this package do you use? The current version needed angular13.

**Comment by ngdevc** [comment]
"ngx-metafizzy-flickity": "^3.0.0",

**Comment by ngdevc** [comment]
which version should I use for angular 10?

**Comment by ngdevc** [comment]
and how can I use this for angular 10?

**Comment by ThRintelen** [comment]
Please try version 2.2.0.
The best way is to update angular in your project :-)
