### ISSUE TITLE
Can't npm install version 6.0.1

### ISSUE THREAD

**Issue by lbcd** [ThRintelen/ngx-metafizzy-flickity#24]
Hello,

https://www.npmjs.com/package/ngx-metafizzy-flickity?activeTab=versions

Max version is 6.0.0 could you do something?

Many thanks in advance

**Comment by ThRintelen** [comment]
Yes, i can.

Now the current version is 6.0.2

**Comment by lbcd** [comment]
So many thanks @ThRintelen it worked for installation but I have an issue on loading now while it worked before

![image](https://github.com/ThRintelen/ngx-metafizzy-flickity/assets/1815136/20849299-b8a5-45ed-8906-7a42348b6805)

I'm trying by myself and if I find a solution I will share it.

**Comment by ThRintelen** [comment]
Hm, i cant see an error if i try it on my machine. Can you create a stackblitz or something like this?

**Comment by lbcd** [comment]
Hello @ThRintelen 
Here is new project with the issue. Hope it can help.
 
[ng16-carousel.zip](https://github.com/ThRintelen/ngx-metafizzy-flickity/files/13215703/ng16-carousel.zip)

**Comment by ThRintelen** [comment]
Can you try version 6.1.3 please?

**Comment by lbcd** [comment]
Hello,

An other error 
![image](https://github.com/ThRintelen/ngx-metafizzy-flickity/assets/1815136/f76735fa-12d2-4ca1-a368-2fb24bb497c1)

I will try to figure out but I'm not sure I can do something from my side.

**Comment by ThRintelen** [comment]
yes, there is no longer a module, please import the directive (standalone) in this version

**Comment by lbcd** [comment]
It works! Many thanks for your help.
