### ISSUE TITLE
how to use fade effect

### ISSUE THREAD

**Issue by thanhhai1998** [ThRintelen/ngx-metafizzy-flickity#3]
hello,how to use fade effect in ngx-metafizzy-flickity,i tried import cdn flickity-fade or import to angular.json but not work, thanks

**Comment by ThRintelen** [comment]
How do you import flickity fade? Can you send an example or create a stackbliz?

**Comment by thanhhai1998** [comment]
> How do you import flickity fade? Can you send an example or create a stackbliz?
i import to angular.json, like this
"styles": [
                            "src/styles.scss",
                            "src/assets/styles/_style.scss",
                            "node_modules/flickity/dist/flickity.min.css",
                            "node_modules/flickity-fade/flickity-fade.css",
                            "node_modules/aos/dist/aos.css"
                        ],
"scripts": [
                            "node_modules/flickity-fade/flickity-fade.js"
                        ]

**Comment by thanhhai1998** [comment]
> How do you import flickity fade? Can you send an example or create a stackbliz?

i import to angular.json, like this
"styles": [
"src/styles.scss",
"src/assets/styles/_style.scss",
"node_modules/flickity/dist/flickity.min.css",
"node_modules/flickity-fade/flickity-fade.css",
"node_modules/aos/dist/aos.css"
],
"scripts": [
"node_modules/flickity-fade/flickity-fade.js"
]

**Comment by marcelocesar** [comment]
Is it possible to use flickity-fade? This issue closed, but I didn't find any solution.

**Comment by ThRintelen** [comment]
Sorry, but i have no solution for you. I tried it but couldn't find a way
